version: "2"

services:
  
  nsqlmongocfg:
    container_name: nsqlmongocfg
    image: "mongo:4.0.5"
    command: mongod --configsvr --replSet mongocfg --bind_ip_all --port 27019
    ports:
      - "27019:27019"
    volumes:
      - ./data/mongocfg:/data/db
  
  nosqlmongoshard:
    container_name: nosqlmongoshard
    image: "mongo:4.0.5"
    command: mongod --shardsvr --replSet mongoshard --bind_ip_all --port 27018
    volumes:
      - ./data/mongoshard:/data/db
    ports:
      - "27018:27018"
  
  mongoserver:
    container_name: mongoserver
    image: "mongo:4.0.5"
    command: mongos --configdb mongocfg/nsqlmongocfg:27019 --bind_ip_all
    volumes:
      - ./data/mongos:/data/db
    ports:
      - "27017:27017"